### ISSUE TITLE
Use repositories instead of packages

### ISSUE THREAD

**Issue by robertdebock** [robertdebock/ansible-role-zabbix#1]
Currently this role refers to package. A snippet from `vars/main.yml`:
```
zabbix_repo:
  CentOS:
    6:
      url: http://repo.zabbix.com/zabbix/3.4/rhel/6/x86_64/zabbix-release-3.4-1.el6.noarch.rpm
```

Switching to repositories will be easier to maintain.
