### ISSUE TITLE
Incorrect database creation: "Specified key was too long"

### ISSUE THREAD

**Issue by robertdebock** [robertdebock/ansible-role-zabbix#8]
According to [the documentation](https://www.zabbix.com/documentation/3.0/manual/appendix/install/db_scripts) the database should be:
```
mysql> create database zabbix character set utf8 collate utf8_bin;
```

**Comment by robertdebock** [comment]
Database creation is not a part of this role, but for anybody else:
```
      mysql_db:
        name: zabbix
        encoding: utf8
        collation: utf8-bin
```
