### ISSUE TITLE
A handler presumes httpd is installed

### ISSUE THREAD

**Issue by robertdebock** [robertdebock/ansible-role-zabbix#9]
```
- name: restart httpd
  service:
    name: "{{ item }}"
    state: restarted
  when:
    - ansible_virtualization_type != "docker"
  with_items:
    - "{{ zabbix_httpd_service[ansible_distribution ~ '-' ~ ansible_distribution_major_version]
      | default(zabbix_httpd_service[ansible_distribution]
      | default(zabbix_httpd_service['default'] )) }}"
```

Even-though httpd is not explicitly installed. Maybe add httpd as an (optional?) dependency.
